esphome:
  name: poolcontrol
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  level: DEBUG
  logs:
    component: ERROR

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "PoolControl Fallback Hotspot"
    password: !secret fallback_ap_password

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_key

globals:
  - id: process_cancelled
    type: bool
    restore_value: no
    initial_value: "false"

sensor:
  - platform: template
    name: "Valve Movement Timer"
    id: valve_timer
    update_interval: never
    accuracy_decimals: 1
    internal: true

script:
  - id: close_valves
    parameters:
      exclude_valve: string
    then:
      - lambda: |-
          std::vector<std::pair<std::string, switch_::Switch*>> valves = {
            {"valve1", id(valve1)},
            {"valve2", id(valve2)},
            {"valve3", id(valve3)}
          };

          for (auto& valve : valves) {
            if (exclude_valve.empty() || valve.first != exclude_valve) {
              ESP_LOGD("valve_control", "Cerrando %s%s", valve.first.c_str(), exclude_valve.empty() ? " (cerrando todas las válvulas)" : (" porque la válvula activa es " + exclude_valve).c_str());
              valve.second->turn_off();
            }
          }

packages:
  pump: !include
    file: packages/pump.pkg/main.yaml

  display: !include
    file: packages/display.pkg/main.yaml

  valve1: !include
    file: packages/valve.pkg/main.yaml
    vars:
      valve_number: 1
      pin_number: 26
      button_pin_number: 4
      valve_id: valve1
      moving_id: valve1_moving

  valve2: !include
    file: packages/valve.pkg/main.yaml
    vars:
      valve_number: 2
      pin_number: 27
      button_pin_number: 5
      valve_id: valve2
      moving_id: valve2_moving

  valve3: !include
    file: packages/valve.pkg/main.yaml
    vars:
      valve_number: 3
      pin_number: 13
      button_pin_number: 15
      valve_id: valve3
      moving_id: valve3_moving

  fill: !include
    file: packages/fill.pkg/main.yaml

